import "./globals.css";

export const metadata = {
  title: "Ticket Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main_bg pt-3 md:pt-6 pb-10 px-0">
        <div className="wrap">{children}</div>
      </body>
    </html>
  );
}
